customevents=LogContext;MqFrm;CPUEvent;MemoryEvent;Search;CPULoad
profiles=ExecutionS;Socket;NewTLAB;OutsideTLAB
jfrdir=/tmp/jfrs
tenant=dev

#h2,grpc,mySQL
storageType=grpc

#h2 config
h2dir=/tmp/h2.db

#mySQL config
mySQL.host=xxxx
mySQL.port=3306
mySQL.user=xxxx
mySQL.pwd=xxxx

#grpc, cantor server
grpc.target=localhost:7443
backup.namespace=gold-files.perf-genie-testing
#backup.namespace=gold-files--monitoring--dev1--us-west-2--dev
backup.events=jstack,json-jstack,top,pidstat,vmstat,netstat,jfr,codecache,ps,iostat,df,proc-meminfo,proc-mounts,proc-modules,proc-loadavg

#filtering
threshold=0.05
filterDepth=4
maxStackDepth=48

#experimental to enable river view and surface views
isExperimental=false
