package perfgenie.utils;

public class ArgusQueries {
    static String substrate = System.getenv("SUBSTRATE");
    static String GCQueryT = "START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-AveGCUsage.OneMinuteAverage{cell=CELL,k8s_pod_name=*,role=app,k8s_container_name=coreapp}:avg:1m-avg";
    static String APTQueryT = "SCALE(" +
            "  DIVIDE(" +
            "    DIFF(" +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              GROUPBYTAG(" +
            "                GROUPBYTAG(" +
            "                  START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestTime.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_pod_name#,#SCALE#,#union#" +
            "                )," +
            "                #k8s_container_name#,#SUM#,#union#" +
            "              )," +
            "              FILL(" +
            "                CULL_BELOW(" +
            "                  GROUPBYTAG(" +
            "                    START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#SUM#,#union#" +
            "                  )," +
            "                  #1#,#value#" +
            "                )," +
            "                #1m#,#0m#,#1#" +
            "              )," +
            "              #k8s_container_name#,#DIVIDE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )," +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            SHIFT(" +
            "              GROUPBYTAG(" +
            "                GROUPBYTAG(" +
            "                  GROUPBYTAG(" +
            "                    START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestTime.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_pod_name#,#SCALE#,#union#" +
            "                  )," +
            "                  #k8s_container_name#,#SUM#,#union#" +
            "                )," +
            "                FILL(" +
            "                  CULL_BELOW(" +
            "                    GROUPBYTAG(" +
            "                      START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#SUM#,#union#" +
            "                    )," +
            "                    #1#,#value#" +
            "                  )," +
            "                  #1m#,#0m#,#1#" +
            "                )," +
            "                #k8s_container_name#,#DIVIDE#" +
            "              )," +
            "              #0m#" +
            "            )," +
            "            #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )" +
            "    )," +
            "    DOWNSAMPLE(" +
            "      ALIASBYREGEX(" +
            "        ALIAS(" +
            "          GROUPBYTAG(" +
            "            GROUPBYTAG(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestTime.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_pod_name#,#SCALE#,#union#" +
            "              )," +
            "              #k8s_container_name#,#SUM#,#union#" +
            "            )," +
            "            FILL(" +
            "              CULL_BELOW(" +
            "                GROUPBYTAG(" +
            "                  START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#SUM#,#union#" +
            "                )," +
            "                #1#,#value#" +
            "              )," +
            "              #1m#,#0m#,#1#" +
            "            )," +
            "            #k8s_container_name#,#DIVIDE#" +
            "          )," +
            "          #:#,#literal#,#CELL#,#literal#" +
            "        )," +
            "        #(.*)::\\{#" +
            "      )," +
            "      #1d-avg#,#0#,#abs#" +
            "    )" +
            "  )," +
            "  #100#" +
            ")\n";
    static String JVMCpuQueryT = "SCALE(" +
            "  DIVIDE(" +
            "    DIFF(" +
            "      DIVIDE(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:Jvm.processCpuLoadPercent.Value{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-sum#,#0#,#abs#" +
            "        )" +
            "      )," +
            "      DIVIDE(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              SHIFT(" +
            "                GROUPBYTAG(" +
            "                  START2:END2:core.aws.INSTANCE.DOMAIN:Jvm.processCpuLoadPercent.Value{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "                )," +
            "                #0m#" +
            "              )," +
            "              #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              SHIFT(" +
            "                GROUPBYTAG(" +
            "                  START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "                )," +
            "                #0m#" +
            "              )," +
            "              #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-sum#,#0#,#abs#" +
            "        )" +
            "      )" +
            "    )," +
            "    DIVIDE(" +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              START1:END1:core.aws.INSTANCE.DOMAIN:Jvm.processCpuLoadPercent.Value{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )," +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-sum#,#0#,#abs#" +
            "      )" +
            "    )" +
            "  )," +
            "  #100#" +
            ")";
    static String containerCpuQueryT = "SCALE(" +
            "  DIVIDE(" +
            "    DIFF(" +
            "      DIVIDE(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              DOWNSAMPLE(" +
            "                GROUPBYTAG(" +
            "                  SCALE(" +
            "                    GROUPBYTAG(" +
            "                      DOWNSAMPLE(" +
            "                        DIVIDE(" +
            "                          RATE(" +
            "                            INCLUDE(" +
            "                              START1:END1:cadvisor.aws.INSTANCE.DOMAIN:container_cpu_usage_seconds_total{k8s_container_name=coreapp,k8s_pod_name=POD1}:avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                            )" +
            "                          )," +
            "                          #60#" +
            "                        )," +
            "                        #2m-avg#" +
            "                      )," +
            "                      PROPAGATE(" +
            "                        INCLUDE(" +
            "                          START1:END1:kube-state-metrics.aws.INSTANCE.DOMAIN:kube_pod_container_resource_requests{k8s_container_name=coreapp,k8s_pod_name=POD1,resource=cpu}:avg:1m-avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                        )," +
            "                        #1m#" +
            "                      )," +
            "                      #k8s_pod_name#,#DIVIDE_V#" +
            "                    )," +
            "                    #100#" +
            "                  )," +
            "                  #k8s_container_name#,#AVERAGE#" +
            "                )," +
            "                #1m-avg#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )" +
            "      )," +
            "      DIVIDE(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              SHIFT(" +
            "                DOWNSAMPLE(" +
            "                  GROUPBYTAG(" +
            "                    SCALE(" +
            "                      GROUPBYTAG(" +
            "                        DOWNSAMPLE(" +
            "                          DIVIDE(" +
            "                            RATE(" +
            "                              INCLUDE(" +
            "                                START2:END2:cadvisor.aws.INSTANCE.DOMAIN:container_cpu_usage_seconds_total{k8s_container_name=coreapp,k8s_pod_name=POD2}:avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                              )" +
            "                            )," +
            "                            #60#" +
            "                          )," +
            "                          #2m-avg#" +
            "                        )," +
            "                        PROPAGATE(" +
            "                          INCLUDE(" +
            "                            START2:END2:kube-state-metrics.aws.INSTANCE.DOMAIN:kube_pod_container_resource_requests{k8s_container_name=coreapp,k8s_pod_name=POD2,resource=cpu}:avg:1m-avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                          )," +
            "                          #1m#" +
            "                        )," +
            "                        #k8s_pod_name#,#DIVIDE_V#" +
            "                      )," +
            "                      #100#" +
            "                    )," +
            "                    #k8s_container_name#,#AVERAGE#" +
            "                  )," +
            "                  #1m-avg#" +
            "                )," +
            "                #0m#" +
            "              )," +
            "              #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              SHIFT(" +
            "                GROUPBYTAG(" +
            "                  START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "                )," +
            "                #0m#" +
            "              )," +
            "              #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )" +
            "      )" +
            "    )," +
            "    DIVIDE(" +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            DOWNSAMPLE(" +
            "              GROUPBYTAG(" +
            "                SCALE(" +
            "                  GROUPBYTAG(" +
            "                    DOWNSAMPLE(" +
            "                      DIVIDE(" +
            "                        RATE(" +
            "                          INCLUDE(" +
            "                            START1:END1:cadvisor.aws.INSTANCE.DOMAIN:container_cpu_usage_seconds_total{k8s_container_name=coreapp,k8s_pod_name=POD1}:avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                          )" +
            "                        )," +
            "                        #60#" +
            "                      )," +
            "                      #2m-avg#" +
            "                    )," +
            "                    PROPAGATE(" +
            "                      INCLUDE(" +
            "                        START1:END1:kube-state-metrics.aws.INSTANCE.DOMAIN:kube_pod_container_resource_requests{k8s_container_name=coreapp,k8s_pod_name=POD1,resource=cpu}:avg:1m-avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                      )," +
            "                      #1m#" +
            "                    )," +
            "                    #k8s_pod_name#,#DIVIDE_V#" +
            "                  )," +
            "                  #100#" +
            "                )," +
            "                #k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #1m-avg#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )," +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )" +
            "    )" +
            "  )," +
            "  #100#" +
            ")";

    static String startupQueryT = "START1:END1:core.aws.INSTANCE.DOMAIN:AppStartup.totalStartupMs{cell=CELL,k8s_pod_name=POD}:avg:1m-avg";

    static String requestCountQueryT = "GROUPBYTAG(START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_pod_name=*}:sum:10m-sum,#cell#,#SUM#)";

    static String requestCountKpodsQueryT = "START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_pod_name=*}:sum:1m-sum";

    static String APTQueryReleaseT = "SCALE(" +
            "  DIVIDE(" +
            "    DIFF(" +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              GROUPBYTAG(" +
            "                GROUPBYTAG(" +
            "                  START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestTime.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_pod_name#,#SCALE#,#union#" +
            "                )," +
            "                #k8s_container_name#,#SUM#,#union#" +
            "              )," +
            "              FILL(" +
            "                CULL_BELOW(" +
            "                  GROUPBYTAG(" +
            "                    START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#SUM#,#union#" +
            "                  )," +
            "                  #1#,#value#" +
            "                )," +
            "                #1m#,#0m#,#1#" +
            "              )," +
            "              #k8s_container_name#,#DIVIDE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )," +
            "      SHIFT(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              SHIFT(" +
            "                GROUPBYTAG(" +
            "                  GROUPBYTAG(" +
            "                    GROUPBYTAG(" +
            "                      START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestTime.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_pod_name#,#SCALE#,#union#" +
            "                    )," +
            "                    #k8s_container_name#,#SUM#,#union#" +
            "                  )," +
            "                  FILL(" +
            "                    CULL_BELOW(" +
            "                      GROUPBYTAG(" +
            "                        START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#SUM#,#union#" +
            "                      )," +
            "                      #1#,#value#" +
            "                    )," +
            "                    #1m#,#0m#,#1#" +
            "                  )," +
            "                  #k8s_container_name#,#DIVIDE#" +
            "                )," +
            "                #0m#" +
            "              )," +
            "              #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        #7d#" +
            "      )" +
            "    )," +
            "    DOWNSAMPLE(" +
            "      ALIASBYREGEX(" +
            "        ALIAS(" +
            "          GROUPBYTAG(" +
            "            GROUPBYTAG(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestTime.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_pod_name#,#SCALE#,#union#" +
            "              )," +
            "              #k8s_container_name#,#SUM#,#union#" +
            "            )," +
            "            FILL(" +
            "              CULL_BELOW(" +
            "                GROUPBYTAG(" +
            "                  START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#SUM#,#union#" +
            "                )," +
            "                #1#,#value#" +
            "              )," +
            "              #1m#,#0m#,#1#" +
            "            )," +
            "            #k8s_container_name#,#DIVIDE#" +
            "          )," +
            "          #:#,#literal#,#CELL#,#literal#" +
            "        )," +
            "        #(.*)::\\{#" +
            "      )," +
            "      #1d-avg#,#0#,#abs#" +
            "    )" +
            "  )," +
            "  #100#" +
            ")";
    static String JVMCpuQueryReleaseT = "SCALE(" +
            "  DIVIDE(" +
            "    DIFF(" +
            "      DIVIDE(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:Jvm.processCpuLoadPercent.Value{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-sum#,#0#,#abs#" +
            "        )" +
            "      )," +
            "      SHIFT(" +
            "        DIVIDE(" +
            "          DOWNSAMPLE(" +
            "            ALIASBYREGEX(" +
            "              ALIAS(" +
            "                SHIFT(" +
            "                  GROUPBYTAG(" +
            "                    START2:END2:core.aws.INSTANCE.DOMAIN:Jvm.processCpuLoadPercent.Value{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "                  )," +
            "                  #0m#" +
            "                )," +
            "                #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "              )," +
            "              #(.*)::\\{#" +
            "            )," +
            "            #1d-avg#,#0#,#abs#" +
            "          )," +
            "          DOWNSAMPLE(" +
            "            ALIASBYREGEX(" +
            "              ALIAS(" +
            "                SHIFT(" +
            "                  GROUPBYTAG(" +
            "                    START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "                  )," +
            "                  #0m#" +
            "                )," +
            "                #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "              )," +
            "              #(.*)::\\{#" +
            "            )," +
            "            #1d-sum#,#0#,#abs#" +
            "          )" +
            "        )," +
            "        #7d#" +
            "      )" +
            "    )," +
            "    DIVIDE(" +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              START1:END1:core.aws.INSTANCE.DOMAIN:Jvm.processCpuLoadPercent.Value{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )," +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-sum#,#0#,#abs#" +
            "      )" +
            "    )" +
            "  )," +
            "  #100#" +
            ")";
    static String containerCpuQueryReleaseT = "SCALE(" +
            "  DIVIDE(" +
            "    DIFF(" +
            "      DIVIDE(" +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              DOWNSAMPLE(" +
            "                GROUPBYTAG(" +
            "                  SCALE(" +
            "                    GROUPBYTAG(" +
            "                      DOWNSAMPLE(" +
            "                        DIVIDE(" +
            "                          RATE(" +
            "                            INCLUDE(" +
            "                              START1:END1:cadvisor.aws.INSTANCE.DOMAIN:container_cpu_usage_seconds_total{k8s_container_name=coreapp,k8s_pod_name=POD1}:avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                            )" +
            "                          )," +
            "                          #60#" +
            "                        )," +
            "                        #2m-avg#" +
            "                      )," +
            "                      PROPAGATE(" +
            "                        INCLUDE(" +
            "                          START1:END1:kube-state-metrics.aws.INSTANCE.DOMAIN:kube_pod_container_resource_requests{k8s_container_name=coreapp,k8s_pod_name=POD1,resource=cpu}:avg:1m-avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                        )," +
            "                        #1m#" +
            "                      )," +
            "                      #k8s_pod_name#,#DIVIDE_V#" +
            "                    )," +
            "                    #100#" +
            "                  )," +
            "                  #k8s_container_name#,#AVERAGE#" +
            "                )," +
            "                #1m-avg#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )," +
            "        DOWNSAMPLE(" +
            "          ALIASBYREGEX(" +
            "            ALIAS(" +
            "              GROUPBYTAG(" +
            "                START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #:#,#literal#,#CELL#,#literal#" +
            "            )," +
            "            #(.*)::\\{#" +
            "          )," +
            "          #1d-avg#,#0#,#abs#" +
            "        )" +
            "      )," +
            "      SHIFT(" +
            "        DIVIDE(" +
            "          DOWNSAMPLE(" +
            "            ALIASBYREGEX(" +
            "              ALIAS(" +
            "                SHIFT(" +
            "                  DOWNSAMPLE(" +
            "                    GROUPBYTAG(" +
            "                      SCALE(" +
            "                        GROUPBYTAG(" +
            "                          DOWNSAMPLE(" +
            "                            DIVIDE(" +
            "                              RATE(" +
            "                                INCLUDE(" +
            "                                  START2:END2:cadvisor.aws.INSTANCE.DOMAIN:container_cpu_usage_seconds_total{k8s_container_name=coreapp,k8s_pod_name=POD2}:avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                                )" +
            "                              )," +
            "                              #60#" +
            "                            )," +
            "                            #2m-avg#" +
            "                          )," +
            "                          PROPAGATE(" +
            "                            INCLUDE(" +
            "                              START2:END2:kube-state-metrics.aws.INSTANCE.DOMAIN:kube_pod_container_resource_requests{k8s_container_name=coreapp,k8s_pod_name=POD2,resource=cpu}:avg:1m-avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                            )," +
            "                            #1m#" +
            "                          )," +
            "                          #k8s_pod_name#,#DIVIDE_V#" +
            "                        )," +
            "                        #100#" +
            "                      )," +
            "                      #k8s_container_name#,#AVERAGE#" +
            "                    )," +
            "                    #1m-avg#" +
            "                  )," +
            "                  #0m#" +
            "                )," +
            "                #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "              )," +
            "              #(.*)::\\{#" +
            "            )," +
            "            #1d-avg#,#0#,#abs#" +
            "          )," +
            "          DOWNSAMPLE(" +
            "            ALIASBYREGEX(" +
            "              ALIAS(" +
            "                SHIFT(" +
            "                  GROUPBYTAG(" +
            "                    START2:END2:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD2,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "                  )," +
            "                  #0m#" +
            "                )," +
            "                #:#,#literal#,#0m-canary-CELL#,#literal#" +
            "              )," +
            "              #(.*)::\\{#" +
            "            )," +
            "            #1d-avg#,#0#,#abs#" +
            "          )" +
            "        )," +
            "        #7d#" +
            "      )" +
            "    )," +
            "    DIVIDE(" +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            DOWNSAMPLE(" +
            "              GROUPBYTAG(" +
            "                SCALE(" +
            "                  GROUPBYTAG(" +
            "                    DOWNSAMPLE(" +
            "                      DIVIDE(" +
            "                        RATE(" +
            "                          INCLUDE(" +
            "                            START1:END1:cadvisor.aws.INSTANCE.DOMAIN:container_cpu_usage_seconds_total{k8s_container_name=coreapp,k8s_pod_name=POD1}:avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                          )" +
            "                        )," +
            "                        #60#" +
            "                      )," +
            "                      #2m-avg#" +
            "                    )," +
            "                    PROPAGATE(" +
            "                      INCLUDE(" +
            "                        START1:END1:kube-state-metrics.aws.INSTANCE.DOMAIN:kube_pod_container_resource_requests{k8s_container_name=coreapp,k8s_pod_name=POD1,resource=cpu}:avg:1m-avg,#.*k8s_pod_name=CELL-casam-app-.*#" +
            "                      )," +
            "                      #1m#" +
            "                    )," +
            "                    #k8s_pod_name#,#DIVIDE_V#" +
            "                  )," +
            "                  #100#" +
            "                )," +
            "                #k8s_container_name#,#AVERAGE#" +
            "              )," +
            "              #1m-avg#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )," +
            "      DOWNSAMPLE(" +
            "        ALIASBYREGEX(" +
            "          ALIAS(" +
            "            GROUPBYTAG(" +
            "              START1:END1:core.aws.INSTANCE.DOMAIN:SFDC_type-Stats-name1-System-name2-trustAptRequestCount.Last_1_Min_Avg{cell=CELL,k8s_container_name=coreapp,k8s_pod_name=POD1,role=app}:avg:1m-avg,#k8s_container_name#,#AVERAGE#" +
            "            )," +
            "            #:#,#literal#,#CELL#,#literal#" +
            "          )," +
            "          #(.*)::\\{#" +
            "        )," +
            "        #1d-avg#,#0#,#abs#" +
            "      )" +
            "    )" +
            "  )," +
            "  #100#" +
            ")";

}
