{
 "title": "Core App Primary Dashboard (Hyperforce / Falcon)",
 "description": "Hyperforce / Falcon version of the core app troubleshooting dashboard.",
 "tags": [
  "core",
  "perfops",
  "falcon",
  "hyperforce",
  "perfops-app-primary"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "substrate",
    "label": "Substrate",
    "query": "service(metrics?expression=$start:$end:sdb.salesforce.*.*.*:global_info_host.cpu_utilization{functional_domain=*,k8s_cluster=*}:avg:1h-avg),jsonpath(value=value.scope)"
   },
   {
    "name": "cell",
    "label": "Cell",
    "query": "type(tagv),scope(core.$substrate.*),metric(java-lang_type-Runtime.Uptime),tag(k8s_container_name=coreapp),tagk(cell),limit(5000)"
   },
   {
    "name": "fi",
    "label": "Falcon Instance",
    "query": "type(scope),scope(core.*),metric(java-lang_type-Runtime.Uptime),tagk(cell),tagv($cell),limit(5000)"
   },
   {
    "name": "fd",
    "label": "Functional Domain",
    "query": "type(scope),scope(core.*),metric(java-lang_type-Runtime.Uptime),tagk(cell),tagv($cell),limit(5000)"
   },
   {
    "name": "cell_old",
    "label": "Cell",
    "query": "service(metrics?expression=$start:$end:sdb.salesforce.$substrate.*.*:global_info_host.cpu_utilization{cell!=none,service_instance!=*restore*}:avg:1h-avg),jsonpath(value = value.tags.cell)"
   },
   {
    "name": "fi_old",
    "label": "Falcon Instance",
    "query": "service(metrics?expression=$start:$end:sdb.salesforce.$substrate.*.*:global_info_host.cpu_utilization{cell=$cell}:avg:1h-avg),jsonpath(value = value.scope) "
   },
   {
    "name": "fd_old",
    "label": "Functional Domain",
    "query": "service(metrics?expression=$start:$end:sdb.salesforce.$substrate.$fi.*:global_info_host.cpu_utilization{cell=$cell,functional_domain=*}:avg:1h-avg),jsonpath(value = value.tags.functional_domain)"
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,10m,30m,1h,24h" },
   { "name": "agg", "label": "Aggregate", "query": "avg,sum,min,max" }
  ]
 },
 "panels": [
  {
   "title": "App Version(s)",
   "type": "stat",
   "description": "Displays all app versions running during the time period specified on the dashboard.\n\nNOTE: When multiple versions are present they are *not* ordered.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBYTAG(\n$start:$end:core.$substrate.$fi.$fd:app.metric{cell=$cell,role=app,release=*,k8s_pod_name=*}:avg:$interval-avg,\n#release#,#SUM#,#UNION#),#release=(.+),.*\\}#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DB Type",
   "type": "stat",
   "description": "Displays all app versions running during the time period specified on the dashboard.\n\nNOTE: When multiple versions are present they are *not* ordered.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Node" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\nALIAS(\nALIASBYTAG(\nSLICE(\nGROUPBYTAG($start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_host.cpu_utilization{k8s_cluster=*,cell=$cell,is_read_write=true,service=sdb,write_scaling_cluster=*}:count,#write_scaling_cluster#,#SUM#,#UNION#),\n#start#,#end-30m#),\n#write_scaling_cluster#),\n#/.*true.*/Write Scaling (WS)/#,#regex#),\n#/.*false.*/High Availability (HA)/#,#regex#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DB SKU",
   "type": "stat",
   "description": "AWS instance type used for SDB servers.",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Node" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBYTAG($start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_host.cpu_utilization{k8s_cluster=*,cell=$cell,k8s_pod_name=*,state=*,instance_type=*,service=sdb}:avg:10m-avg,#instance_type#,#SUM#,#UNION#),#(.+):#)\n",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "App Instances",
   "type": "stat",
   "description": "Number of containers running the core app. This displays the last value in the time range.",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "SUM($start:$end:core.$substrate.$fi.$fd:java-lang_type-Runtime.Uptime{role=app,cell=$cell,k8s_pod_name=*}:count:30m-max,#union#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "App SKU",
   "type": "stat",
   "description": "AWS instance type used for app servers.",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "title": "App Heap Size",
   "type": "stat",
   "description": "JVM heap size in GB for the core app instances. \n\nIn the unlikely scenario that there are different heap sizes for different app servers this will report the highest value at the end of the time range.",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "HIGHEST(\n  $start:$end:core.$substrate.$fi.$fd:java-lang_type-Memory.HeapMemoryUsage_max{cell=$cell,k8s_container_name=coreapp,k8s_pod_name=*,role=app}:avg:$interval-avg,#1#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "Number of requests active across the instance, which could be synchronous or asynchronous.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    SUM(\n      $start:$end:core.$substrate.$fi.$fd:SFDC_type-Active_Requests.NumActiveRequests{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,\n      #union#),\n  #$interval-$agg#),\n#active_requests#,#literal#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Request Volume (requests / second)",
   "type": "timeseries",
   "description": "Number of requests completing per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #60#\n    ),\n    #$interval-$agg#),\n  #total_requests#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-SyncServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #60#\n    ),\n    #$interval-$agg#),\n  #synchronous_requests#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "APT Dissection (ms / request)",
   "type": "timeseries",
   "description": "Overall APT broken down by time spent in different subsystems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-WALL_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #wall_time#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-APP_CPU_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #app_cpu_time#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            SCALE($start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.TimeEvent-DB_TOTAL_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max,#0.000001#)\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #db_total_time#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.OracleStat-DB_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #ora_db_time#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            SCALE($start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.TimeEvent-TRANSACTIONAL_CACHE{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max,#0.000001#)\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #transactional_cache#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            SCALE($start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.TimeEvent-MEMCACHED{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max,#0.000001#)\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #memcached#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ApexLogMetric-CALLOUT_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #apex_callout#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            SCALE($start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.TimeEvent-REDIS{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max,#0.000001#)\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #redis#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            SCALE($start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.TimeEvent-PHOENIX_EXEC_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max,#0.000001#)\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #phoenix_hbase_query#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-SEARCH_QUERY_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #search_query#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-SAFEPOINT_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #safepoint#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-GC_TIME{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      CULL_BELOW(\n        SUM(\n          CULL_BELOW(\n            RATE(\n              $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:none:1m-max\n            ),\n            #0#,#value#\n          ),\n          #union#\n        ),\n        #1#,#value#\n      ),\n      #union#,#0#\n    ),\n    #$interval-$agg#\n  ),\n  #gc_pause#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "APT By Container",
   "type": "graph",
   "description": "Average response times from individual app containers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYTAG(\n    GROUPBYTAG(\n      RATE(\n            PROPAGATE($start:$end:core.$substrate.$fi.$fd:SFDC_type-SyncServerMetrics.LogMetric-WALL_TIME{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,#1m#)\n        ),\n      RATE(\n            PROPAGATE($start:$end:core.$substrate.$fi.$fd:SFDC_type-SyncServerMetrics.LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,#1m#)\n        ),\n      #k8s_pod_name#,#DIVIDE#\n      ),\n    #k8s_pod_name#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Login Success / Failure (count / minute)",
   "type": "timeseries",
   "description": "Number of successful or failed logins per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-Login-name2-Success.Last1min{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg,#union#\n      ),\n    #$interval-$agg#\n  ),\n#login_success#,#literal#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-Login-name2-Failure.Last1min{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg,#union#\n      ),\n    #$interval-$agg#\n  ),\n#login_failure#,#literal#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Application Errors (count / minute)",
   "type": "timeseries",
   "description": "Counters of serious errors generated at the application tier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ExtendedCounterMetric-CONCURRENT_APEX_ERRORS{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #$interval-$agg#\n    ),\n    #concurrent_per_org_apex_errors#,#literal#\n  )",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ExtendedCounterMetric-CANCELLED_REQUESTS{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #$interval-$agg#\n    ),\n    #cancelled_requests#,#literal#\n  )",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ExtendedCounterMetric-CONNECTION_POOL_ERRORS{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #$interval-$agg#\n    ),\n    #connection_pool_errors#,#literal#\n  )",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ExtendedCounterMetric-ROW_LOCK_TIMEOUTS{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #$interval-$agg#\n    ),\n    #row_lock_timeouts#,#literal#\n  )",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n    DOWNSAMPLE(\n      SUM(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ExtendedCounterMetric-CONCURRENT_UI_REQUEST_ERRORS{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n          ),\n          #0#,#value#\n        ),\n        #union#\n      ),\n      #$interval-$agg#\n    ),\n    #concurrent_ui_errors#,#literal#\n  )",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Requests by Type (count / sec)",
   "type": "timeseries",
   "description": "Request rate broken down by log record type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      GROUPBY(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics-name1-[U|V|A].LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:10m-max\n          ),\n          #0#,#value#\n        ),\n        #SFDC_type-ServerMetrics-name1-(\\S+?).LogMetric-COUNT#,#sum#,#union#\n      ),\n      #60#\n    ),\n    #$interval-$agg#\n  ),\n  #request_count#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      GROUPBY(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics-name1-[apars|aprst|R].LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:10m-max\n          ),\n          #0#,#value#\n        ),\n        #SFDC_type-ServerMetrics-name1-(\\S+?).LogMetric-COUNT#,#sum#,#union#\n      ),\n      #60#\n    ),\n    #$interval-$agg#\n  ),\n  #request_count#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      GROUPBY(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics-name1-[a|vfrmt].LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:10m-max\n          ),\n          #0#,#value#\n        ),\n        #SFDC_type-ServerMetrics-name1-(\\S+?).LogMetric-COUNT#,#sum#,#union#\n      ),\n      #60#\n    ),\n    #$interval-$agg#\n  ),\n  #request_count#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  DOWNSAMPLE(\n    DIVIDE(\n      GROUPBY(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics-name1-[OTHER|UNKNOWN].LogMetric-COUNT{role=app,cell=$cell,k8s_pod_name=*}:max:10m-max\n          ),\n          #0#,#value#\n        ),\n        #SFDC_type-ServerMetrics-name1-(\\S+?).LogMetric-COUNT#,#sum#,#union#\n      ),\n      #60#\n    ),\n    #$interval-$agg#\n  ),\n  #request_count#,#literal#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Ping Down Status by Host (SEE DESCRIPTION)",
   "type": "graph",
   "description": "Status code for app servers that ping down in a given minute. No information is provided if a host does not ping down. See the table below for the meaning of different status codes.\n\nCodes are current as of Mar. 2022 / 236 release.\n\n| Code | Reason |\n| --- | --- |\n| 0 | NOT UPDATED |\n| 1 | ALIVE |\n| 2 | SHUTTING DOWN |\n| 3 | LB OFFLINE |\n| 4 | SPINMODE |\n| 5 | DCP WAITING FOR PERMITS |\n| 6 | BIG RED BUTTON |\n| 7 | ALL RAC NODE DOWN PAUSE |\n| 8 | SR POD |\n| 9 | SERVER BUSY PATTERN |\n| 10 | BUSY JVM WARM UP |\n| 11 | BUSY APEX WARM UP |\n| 12 | BUSY CENTRIFUGE WARM UP |\n| 20 | BUSY HIGH CPU |\n| 21 | BUSY HIGH GC |\n| 22 | BUSY DISK FULL |\n| 23 | BUSY DB CONN POOL BUSY |\n| 24 | BUSY LOGGING QUEUE FULL |\n| 25 | BUSY FFX SERVER WAIT TIME |\n| 26 | BUSY CLOSED BY INTERRUPT EXCEPTION |\n| 27 | THREAD POOL SATURATION |\n| 30 | BUSY UNKNOWN REASON |\n| 31 | BUSY NULL REASON |\n| 32 | BUSY UNHEALTHY SHERPA |\n| 41 | NON PROD TEST HOOK PING STATUS |\n| 42 | NON PROD TEST PING PAGE |\n| 44 | UNKNOWN |\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  CULL_BELOW(\n    $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-System-name2-PingStatusReasonCode.CurrentSize{role=app,cell=$cell,k8s_pod_name=*}:max:$interval-max,\n    #1.01#,#value#\n  ),\n#k8s_pod_name#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Core App Autoscaling Status",
   "type": "timeseries",
   "description": "If HPA is not enabled this panel will have no data. Note that 'Current Replicas' does not reflect coreapp servers added due to release activity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "currentTransform": { "metricName": "max_replicas", "scopeName": "hpa", "type": "ALIAS" },
     "downsampleAggregator": "avg",
     "downsampleInterval": "$interval",
     "metric": "kube_horizontalpodautoscaler_spec_max_replicas",
     "queryMode": "default",
     "rawSql": "$start:$end:kube-state-metrics.aws.$fi.$fd:kube_hpa_spec_max_replicas{k8s_namespace=core-on-sam,hpa=$cell-casam-app}:avg:1m-avg",
     "scope": "kube-state-metrics.$substrate.$fi.$fd",
     "tags": {
      "horizontalpodautoscaler": "$cell-casam-app",
      "k8s_namespace": "core-on-sam"
     },
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleInterval": "$interval",
     "metric": "kube_horizontalpodautoscaler_spec_min_replicas",
     "queryMode": "default",
     "rawSql": "$start:$end:kube-state-metrics.aws.$fi.$fd:kube_hpa_spec_min_replicas{k8s_namespace=core-on-sam,hpa=$cell-casam-app}:avg:1m-avg",
     "scope": "kube-state-metrics.$substrate.$fi.$fd",
     "tags": {
      "horizontalpodautoscaler": "$cell-casam-app",
      "k8s_namespace": "core-on-sam"
     },
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "max",
     "downsampleAggregator": "max",
     "downsampleInterval": "$interval",
     "metric": "kube_horizontalpodautoscaler_status_desired_replicas",
     "queryMode": "default",
     "scope": "kube-state-metrics.$substrate.$fi.$fd",
     "tags": {
      "horizontalpodautoscaler": "$cell-casam-app",
      "k8s_namespace": "core-on-sam"
     },
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "max",
     "downsampleAggregator": "max",
     "downsampleInterval": "$interval",
     "metric": "kube_horizontalpodautoscaler_status_current_replicas",
     "queryMode": "default",
     "scope": "kube-state-metrics.$substrate.$fi.$fd",
     "tags": {
      "horizontalpodautoscaler": "$cell-casam-app",
      "k8s_namespace": "core-on-sam"
     },
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "max",
     "currentTagKey": "deployment_namespace",
     "currentTagValue": "core-on-sam",
     "currentTransform": { "tagGroupBy": "deployment_name", "transformGroupBy": "MAX", "type": "GROUPBYTAG" },
     "downsampleAggregator": "max",
     "downsampleInterval": "$interval",
     "metric": "predicted_replicas",
     "queryMode": "expression",
     "rawSql": "GROUPBY($start:$end:mars.sam.$substrate.$fi.$fd:predicted_replicas{deployment_name=$cell-casam-app-*,deployment_namespace=core-on-sam}:max:$interval-max,#:(\\w+)\\{.*(=\\w+)-casam.*#,#MAX#)",
     "scope": "mars.sam.$substrate.$fi.$fd",
     "tags": { "deployment_name": "$cell-casam-app-*" },
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Database Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  { "title": "SDB Topology", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "SDB Primary (HA) / Cluster Manager (WS)",
   "type": "stat",
   "description": "Shows the primary SDB node when the database is a high-availability (HA) cluster or the cluster master (CM) for a write-scale (WS) cluster.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "CULL_BELOW(\n  RECENT(\n    ALIASBYTAG(\n      FILL(\n        $start:($end-2m):sdd-controller.none.$substrate.$fi.$fd:sdb.sdd.controller.master-discoverable{cell=$cell,service=sdb,container=*,k8s_cluster=*}:max:1m-max,\n        #1m#, #0s#, #0#\n      ),\n      #container#\n    )\n  ),\n  #1#, #value#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SDB Instances (Read/Write)",
   "type": "table",
   "description": "SDB Read/Write instance information.\n\nFor HA instances there will only be one entry here. For WS instances there will be multiple entires and the log owner / cluster manager will have the state \"master\" rather than local.",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 45 },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  ALIASBYTAG(\n    GROUPBYTAG(\n      $start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_hardware.is_vm{k8s_cluster=*,cell=$cell,k8s_pod_name=sdb-*-[0-9]*,state=*,instance_type=*,zone=*,device=*,is_read_write=true}:avg,\n      #k8s_pod_name#, #instance_type#, #zone#, #device#, #state#, #RECENT#\n    ),\n    #k8s_pod_name#, #instance_type#, #zone#, #device#, #state#\n  ),\n  #/,/ : /#, #regex#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  ALIASBYTAG(\n    GROUPBYTAG(\n      $start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_hardware.is_vm{k8s_cluster=*,cell=$cell,k8s_pod_name=sdb-*-[0-9]*,state=*,instance_type=*,zone=*,device=*,is_read_write=true}:avg,\n      #k8s_pod_name#, #instance_type#, #zone#, #device#, #state#, #RECENT#\n    ),\n    #k8s_pod_name#, #instance_type#, #zone#, #device#, #state#\n  ),\n  #/,/ : /#, #regex#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SDB Instances (Standby)",
   "type": "table",
   "description": "SDB standby instance information.",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 45 },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  ALIASBYTAG(\n    GROUPBYTAG(\n      $start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_hardware.is_vm{k8s_cluster=*,cell=$cell,k8s_pod_name=sdb-*-[0-9]*,state=*,instance_type=*,zone=*,device=*,is_read_write=false}:avg,\n      #k8s_pod_name#, #instance_type#, #zone#, #device#, #state#, #RECENT#\n    ),\n    #k8s_pod_name#, #instance_type#, #zone#, #device#, #state#\n  ),\n  #/,/ : /#, #regex#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SDB Version",
   "type": "stat",
   "description": "Version of SDB running on the cluster.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBYTAG($start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_host.cpu_utilization{k8s_cluster=*,cell=$cell,k8s_pod_name=*,state=*,version=*,service=sdb}:avg:10m-avg,#version#,#SUM#,#UNION#),#(.+):#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "SDB CPU & Connections", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "SDB CPU Utilization ($interval-$agg, read/write nodes only)",
   "type": "timeseries",
   "description": "System CPU utilization SDB instances, standby/read-only nodes are not included.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYTAG(\n    $start:$end:sfms_system.salesforce.$substrate.$fi.$fd:cpustats.utilization_rate{is_read_write=true,cell=$cell,k8s_pod_name=*}:max:1m-max,#k8s_pod_name#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SDB Current Connections, % of Max ($interval-$agg, read/write nodes only)",
   "type": "timeseries",
   "description": "Sum of current and maximum configured connections on read/write SDB instances. \n\nThese numbers are from SDB statistics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    CULL_BELOW(\n      GROUPBYTAG(\n        $start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_process.current_connections{cell=$cell,is_read_write=true,k8s_pod_name=*}:max:1m-max,\n        $start:$end:sdb.salesforce.$substrate.$fi.$fd:global_info_process.configured_max_connections{cell=$cell,is_read_write=true,k8s_pod_name=*}:max:1m-max,\n        #k8s_pod_name#,\n        #DIVIDE#,\n        #union#,\n        #-1#\n      ),\n      #0#,\n      #value#\n    ),\n    #$interval-$agg#\n  ),\n  #k8s_pod_name#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "SDB Aggregate Time Consumption", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Aggregate SDB End-To-End Time Categories (time per minute, $interval-$agg)",
   "type": "graph",
   "description": "Aggregate SDB time consumption broken down by high-level categories. (Ex. CPU, wait, I/O, etc.)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(\n    GROUPBYTAG(\n      RATE(\n        EXCLUDE(\n          CULL_BELOW(\n            JOIN(\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[a|b]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[c|d]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[e|f]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[g|h]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[i|j]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[k|l]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[m|n]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[o|p]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[q|r]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[s|t]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[u|v]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[w|x]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[y|z]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*,e2e_category=*}:avg:1m-avg\n            ),\n            #1#,\n            #value#\n          ),\n          #.*(Count|recv_command_wait|ws_dispatcher_wait|epoch_gen_sleep|daemon_unattributed).*#\n        )\n      ),\n      #e2e_category#,#SUM#,#UNION#\n    ),\n    #(.+):#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Aggregate SDB End-To-End Time Groups (time per minute, $interval-$agg)",
   "type": "graph",
   "description": "Aggregate SDB time consumption broken down by time category. (CPU, wait, I/O, etc.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(\n    GROUPBY(\n      RATE(\n        EXCLUDE(\n          CULL_BELOW(\n            JOIN(\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[a|b]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[c|d]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[e|f]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[g|h]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[i|j]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[k|l]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[m|n]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[o|p]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[q|r]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[s|t]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[u|v]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[w|x]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[y|z]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg\n            ),\n            #1#,\n            #value#\n          ),\n          #.*(Count|recv_command_wait|ws_dispatcher_wait|epoch_gen_sleep|daemon_unattributed).*#\n        )\n      ),\n      #.*end2end_time_stats.([^_{]+)#,#SUM#,#UNION#\n    ),\n    #(.*):#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Aggregate SDB End-To-End Time Details (time per minute, $interval-$agg)",
   "type": "graph",
   "description": "Aggregate SDB time consumption broken down by specific time category. (Ex. memstore_scan, memstore_fetch, etc.)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(\n    GROUPBY(\n      RATE(\n        EXCLUDE(\n          CULL_BELOW(\n            JOIN(\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[a|b]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[c|d]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[e|f]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[g|h]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[i|j]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[k|l]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[m|n]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[o|p]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[q|r]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[s|t]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[u|v]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[w|x]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg,\n              $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.[y|z]*{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:sum:1m-avg\n            ),\n            #1#,\n            #value#\n          ),\n          #.*(Count|recv_command_wait|ws_dispatcher_wait|epoch_gen_sleep).*#\n        )\n      ),\n      #.*end2end_time_stats.(.*)\\{#,#SUM#,#UNION#\n      ),\n    #(.*):#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SDB Memstore",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "<div align=\"center\">Memstore is 32 GB in size with a 5% defragmentation reserve.</div>"
   }
  },
  {
   "title": "Memstore Usage (% used, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(\n    ALIAS(\n      DIVIDE(\n        ABSOLUTE(\n          DIFF(\n            MIN(\n              $start:$end:sdb.salesforce.aws.$fi.$fd:memstore_stats.freeBytes{k8s_cluster=*,cell=$cell,is_read_write=[true|t],state=*,k8s_pod_name_nogen=sdb-*}:avg:1m-min\n            ),\n            #34359738368#\n          )\n        ),\n        #34359738368#\n      ),\n      #Percent Used#,#literal#\n    ),\n    #:(.+)\\{#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memstore Usage Details (space used, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  JOIN(\n    ALIASBYREGEX(\n      MAX(\n        $start:$end:sdb.salesforce.aws.$fi.$fd:memstore_operation_stats.memstoreUncommittedBytes{cell=$cell,is_read_write=true,state=master,k8s_cluster=*}:avg:1m-avg\n      ),\n      #:memstore_operation_stats.(.*)\\{#\n    ),\n    ALIASBYREGEX(\n      MAX(\n        $start:$end:sdb.salesforce.aws.$fi.$fd:memstore_operation_stats.memstoreUnflushedBytes{cell=$cell,is_read_write=true,state=master,k8s_cluster=*}:avg:1m-avg\n      ),\n      #:memstore_operation_stats.(.*)\\{#\n    )\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "SDB I/O", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "I/O Rate (operations per second, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(DIVIDE(GROUPBY(\n  RATE($start:$end:sdb.salesforce.aws.$fi.$fd:keystone_store_stats.*Count{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:avg:$interval-avg),\n  #:[^\\.]*.(.*)Count\\{.*#,#SUM#,#UNION#),#60#),#(.+):#),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Random Read Latency (time per read, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(\n    ALIAS(\n      DIVIDE(\n        SUM(\n          RATE(\n            $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.store_rand_read{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:avg:1m-avg\n          )\n        ),\n        SUM(\n          RATE(\n            $start:$end:sdb.salesforce.aws.$fi.$fd:end2end_time_stats.store_rand_readCount{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=sdb-*,is_read_write=[true|t],state=*}:avg:1m-avg\n          )\n        )\n      ),\n      #SDBRandomReadLatency#,#literal#\n    ),\n    #.*:([a-zA-Z_]*)#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "SDB Locking & Synchronization", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Spinlocks (count and time per minute, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBY(RATE($start:$end:sdb.salesforce.aws.$fi.$fd:spin_wait_stats.*AcquireCount{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:none:$interval-$agg),#.*(AcquireCount).*#,#SUM#,#union#),#(.*):.*#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBY(RATE($start:$end:sdb.salesforce.aws.$fi.$fd:spin_wait_stats.*SpinCount{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:none:$interval-$agg),#.*(SpinCount).*#,#SUM#,#union#),#(.*):.*#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBY(RATE($start:$end:sdb.salesforce.aws.$fi.$fd:spin_wait_stats.*SleepCount{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:none:$interval-$agg),#.*(SleepCount).*#,#SUM#,#union#),#(.*):.*#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYREGEX(GROUPBY(RATE($start:$end:sdb.salesforce.aws.$fi.$fd:spin_wait_stats.*SleepTime{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:avg:$interval-$agg),#.*(SleepTime).*#,#SUM#,#union#),#(.*):.*#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Spinlock Spin Count (count per minute, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(GROUPBY(\n  RATE($start:$end:sdb.salesforce.aws.$fi.$fd:spin_wait_stats.*SpinCount{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:avg:1m-avg),\n  #.*:spin_wait_stats.(.*)_SpinCount\\{#,#SUM#,#UNION#),#(.+):#),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Spinlock Sleep Time (time per minute, $interval-$agg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYREGEX(GROUPBY(\n  RATE($start:$end:sdb.salesforce.aws.$fi.$fd:spin_wait_stats.*SleepTime{k8s_cluster=*,cell=$cell,k8s_pod_name_nogen=*,is_read_write=true,state=*}:avg:1m-avg),\n  #.*:spin_wait_stats.(.*)_SleepTime\\{#,#SUM#,#UNION#),#(.+):#),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "coreapp Primary Container Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 }
  },
  {
   "title": "coreapp Container Information",
   "type": "table",
   "description": "Information about the primary containers in the pod.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 122 },
   "options": {
    "content": "##### coreapp Container CPU Utilization"
   }
  },
  {
   "title": "coreapp Container CPU Utilization (% of request)",
   "type": "timeseries",
   "description": "Percentage of CPU requested CPU used per minute. Note that it's possible for containers to use greater than 100% of CPU request/quota and throttling is not guaranteed to occur unless the *limit* is exceeded. ",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 123.25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "WITH\n  kube_state_hourly AS (\n    SELECT\n      DATE_TRUNC('hour', kube_state_raw.\"__time\") AS \"__time\",\n      kube_state_raw.k8s_pod_name,\n      kube_state_raw.k8s_container_name,\n      kube_state_raw.falcon_instance,\n      kube_state_raw.functional_domain_instance,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_requests,\n            '$.cpu.core'\n          ) AS DOUBLE\n        )\n      ) AS container_cpu_cores_request,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_requests,\n            '$.memory.byte'\n          ) AS DOUBLE\n        )\n      ) AS container_memory_bytes_request,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_limits,\n            '$.cpu.core'\n          ) AS DOUBLE\n        )\n      ) AS container_cpu_cores_limit,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_limits,\n            '$.memory.byte'\n          ) AS DOUBLE\n        )\n      ) AS container_memory_bytes_limit\n    FROM\n      (\n        SELECT\n          __time,\n          k8s_pod_name,\n          k8s_container_name,\n          falcon_instance,\n          functional_domain_instance,\n          kube_pod_container_resource_limits,\n          kube_pod_container_resource_requests\n        FROM\n          KubeState\n        WHERE\n          __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\n          AND __time <= MILLIS_TO_TIMESTAMP(${__to})\n          AND k8s_container_name = 'coreapp'\n          AND falcon_instance = '$fi'\n          AND functional_domain_instance = '$fd'\n          AND k8s_pod_name LIKE '$cell-casam-app%'\n      ) AS kube_state_raw\n    GROUP BY\n      1,\n      2,\n      3,\n      4,\n      5\n  ),\n  cadvisor_metrics AS (\n    SELECT\n      __time,\n      previous_timestamp,\n      k8s_pod_name,\n      k8s_container_name,\n      falcon_instance,\n      functional_domain_instance,\n      instance_type,\n      zone,\n      timestamp_seconds_diff,\n      cpu_seconds_diff,\n      cfs_throttled_seconds_diff,\n      cpu_cfs_throttled_periods_diff,\n      cpu_cfs_periods_diff,\n      oom_events_diff,\n      memory_usage_bytes,\n      device,\n      sockets,\n      file_descriptors\n    FROM\n      (\n        SELECT\n          -- Propagate up raw metrics.\n          *,\n          -- Elapsed seconds between metrics.\n          (CAST(TIMESTAMPDIFF (MILLISECOND, previous_timestamp, __time) AS DOUBLE) / 1000) AS timestamp_seconds_diff,\n          (\n            cpu_usage_seconds_total - previous_cpu_usage_seconds_total\n          ) AS cpu_seconds_diff,\n          -- Elapsed CFS throttled seconds.\n          (\n            cpu_cfs_throttled_seconds_total - previous_cpu_cfs_throttled_seconds_total\n          ) AS cfs_throttled_seconds_diff,\n          -- Elapsed CFS periods. (Total, not throttled.)\n          (\n            cpu_cfs_periods_total - previous_cpu_cfs_periods_total\n          ) AS cpu_cfs_periods_diff,\n          -- Throttled CFS periods.\n          (\n            cpu_cfs_throttled_periods_total - previous_cpu_cfs_throttled_periods_total\n          ) AS cpu_cfs_throttled_periods_diff,\n          -- OOM events.\n          (\n            oom_events_total - previous_oom_events_total\n          ) AS oom_events_diff\n        FROM\n          (\n            SELECT\n              *,\n              LAG(\"__time\", 1, \"__time\") OVER w AS previous_timestamp,\n              LAG(\n                cpu_usage_seconds_total,\n                1,\n                cpu_usage_seconds_total\n              ) OVER w AS previous_cpu_usage_seconds_total,\n              LAG(\n                cpu_cfs_throttled_seconds_total,\n                1,\n                cpu_cfs_throttled_seconds_total\n              ) OVER w AS previous_cpu_cfs_throttled_seconds_total,\n              LAG (\n                cpu_cfs_throttled_periods_total,\n                1,\n                cpu_cfs_throttled_periods_total\n              ) OVER w AS previous_cpu_cfs_throttled_periods_total,\n              LAG(\n                cpu_cfs_periods_total,\n                1,\n                cpu_cfs_periods_total\n              ) OVER w AS previous_cpu_cfs_periods_total,\n              LAG(\n                oom_events_total,\n                1,\n                oom_events_total\n              ) OVER w AS previous_oom_events_total\n            FROM\n              (\n                SELECT\n                  \"__time\",\n                  k8s_pod_name,\n                  k8s_container_name,\n                  falcon_instance,\n                  functional_domain_instance,\n                  instance_type,\n                  zone,\n                  device,\n                  container_cpu_cfs_periods_total AS cpu_cfs_periods_total,\n                  container_cpu_cfs_throttled_periods_total AS cpu_cfs_throttled_periods_total,\n                  container_cpu_cfs_throttled_seconds_total AS cpu_cfs_throttled_seconds_total,\n                  container_cpu_usage_seconds_total AS \"cpu_usage_seconds_total\",\n                  container_file_descriptors AS file_descriptors,\n                  container_sockets AS sockets,\n                  container_oom_events_total AS oom_events_total,\n                  container_memory_usage_bytes AS memory_usage_bytes\n                FROM\n                  cAdvisor\n                WHERE\n                  __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\n                  AND __time <= MILLIS_TO_TIMESTAMP(${__to})\n                  AND k8s_container_name = 'coreapp'\n                  AND falcon_instance = '$fi'\n                  AND functional_domain_instance = '$fd'\n                  AND k8s_pod_name LIKE '$cell-casam-app-%'\n              )\n            WINDOW\n              w AS (\n                PARTITION BY\n                  falcon_instance,\n                  functional_domain_instance,\n                  k8s_pod_name,\n                  k8s_container_name,\n                  instance_type,\n                  zone,\n                  device\n                ORDER BY\n                  \"__time\" ASC\n              )\n          )\n      )\n  )\nSELECT\n  --time_floor(cadvisor_metrics.__time, 'pt12h') AS \"timestamp\",\n  time_floor(cadvisor_metrics.__time, 'pt$interval') AS \"timestamp\",\n  cadvisor_metrics.k8s_pod_name,\n  cadvisor_metrics.k8s_container_name,\n  cadvisor_metrics.falcon_instance,\n  cadvisor_metrics.functional_domain_instance AS functional_domain,\n  cadvisor_metrics.instance_type,\n  cadvisor_metrics.zone,\n  cadvisor_metrics.device,\n  AVG(GREATEST(timestamp_seconds_diff, 0)) AS seconds_from_previous_cadvisor_metric,\n  MAX(container_cpu_cores_request) AS container_cpu_cores_request,\n  MAX(container_cpu_cores_limit) AS container_cpu_cores_limit,\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_request) * 100), 0)) AS \"CPU Quota Usage\",\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_limit) * 100), 0)) AS cpu_pct_limit_utilization,\n  MAX(memory_usage_bytes) AS memory_usage_bytes,\n  MAX(container_memory_bytes_request) AS container_memory_bytes_request,\n  MAX(container_memory_bytes_limit) AS container_memory_bytes_limit,\n  MAX(((memory_usage_bytes / container_memory_bytes_request) * 100)) AS container_memory_pct_request_utilization,\n  MAX(((memory_usage_bytes / container_memory_bytes_limit) * 100)) AS container_memory_pct_limit_utilization,\n  SUM(GREATEST(oom_events_diff, 0)) AS oom_events_diff,\n  AVG(GREATEST(cfs_throttled_seconds_diff, 0)/(timestamp_seconds_diff/60)) AS cfs_throttled_seconds_per_minute,\n  AVG(GREATEST(cpu_cfs_throttled_periods_diff, 0)) AS cpu_cfs_throttled_periods_diff,\n  AVG(GREATEST(cpu_cfs_periods_diff, 0)) AS cpu_cfs_periods_diff,\n  AVG(((GREATEST(cpu_cfs_throttled_periods_diff, 0) / cpu_cfs_periods_diff) * 100)) AS cpu_cfs_pct_throttled_periods,\n  AVG(sockets) AS sockets,\n  AVG(file_descriptors) AS file_descriptors\nFROM\n  cadvisor_metrics\n  LEFT JOIN kube_state_hourly ON (\n    cadvisor_metrics.falcon_instance = kube_state_hourly.falcon_instance\n    AND cadvisor_metrics.functional_domain_instance = kube_state_hourly.functional_domain_instance\n    AND cadvisor_metrics.k8s_pod_name = kube_state_hourly.k8s_pod_name\n    AND cadvisor_metrics.k8s_container_name = kube_state_hourly.k8s_container_name\n    AND DATE_TRUNC('hour', cadvisor_metrics.__time) = kube_state_hourly.__time\n  )\nGROUP BY\n  1, 2, 3, 4, 5, 6, 7, 8",
      "queryType": "sql"
     },
     "eventType": "cAdvisor",
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"WITH\\n  kube_state_hourly AS (\\n    SELECT\\n      DATE_TRUNC('hour', kube_state_raw.\\\"__time\\\") AS \\\"__time\\\",\\n      kube_state_raw.k8s_pod_name,\\n      kube_state_raw.k8s_container_name,\\n      kube_state_raw.falcon_instance,\\n      kube_state_raw.functional_domain_instance,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_requests,\\n            '$.cpu.core'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_cpu_cores_request,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_requests,\\n            '$.memory.byte'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_memory_bytes_request,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_limits,\\n            '$.cpu.core'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_cpu_cores_limit,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_limits,\\n            '$.memory.byte'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_memory_bytes_limit\\n    FROM\\n      (\\n        SELECT\\n          __time,\\n          k8s_pod_name,\\n          k8s_container_name,\\n          falcon_instance,\\n          functional_domain_instance,\\n          kube_pod_container_resource_limits,\\n          kube_pod_container_resource_requests\\n        FROM\\n          KubeState\\n        WHERE\\n          __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\\n          AND __time <= MILLIS_TO_TIMESTAMP(${__to})\\n          AND k8s_container_name = 'coreapp'\\n          AND falcon_instance = '$fi'\\n          AND functional_domain_instance = '$fd'\\n          AND k8s_pod_name LIKE '$cell-casam-app%'\\n      ) AS kube_state_raw\\n    GROUP BY\\n      1,\\n      2,\\n      3,\\n      4,\\n      5\\n  ),\\n  cadvisor_metrics AS (\\n    SELECT\\n      __time,\\n      previous_timestamp,\\n      k8s_pod_name,\\n      k8s_container_name,\\n      falcon_instance,\\n      functional_domain_instance,\\n      instance_type,\\n      zone,\\n      timestamp_seconds_diff,\\n      cpu_seconds_diff,\\n      cfs_throttled_seconds_diff,\\n      cpu_cfs_throttled_periods_diff,\\n      cpu_cfs_periods_diff,\\n      oom_events_diff,\\n      memory_usage_bytes,\\n      device,\\n      sockets,\\n      file_descriptors\\n    FROM\\n      (\\n        SELECT\\n          -- Propagate up raw metrics.\\n          *,\\n          -- Elapsed seconds between metrics.\\n          (CAST(TIMESTAMPDIFF (MILLISECOND, previous_timestamp, __time) AS DOUBLE) / 1000) AS timestamp_seconds_diff,\\n          (\\n            cpu_usage_seconds_total - previous_cpu_usage_seconds_total\\n          ) AS cpu_seconds_diff,\\n          -- Elapsed CFS throttled seconds.\\n          (\\n            cpu_cfs_throttled_seconds_total - previous_cpu_cfs_throttled_seconds_total\\n          ) AS cfs_throttled_seconds_diff,\\n          -- Elapsed CFS periods. (Total, not throttled.)\\n          (\\n            cpu_cfs_periods_total - previous_cpu_cfs_periods_total\\n          ) AS cpu_cfs_periods_diff,\\n          -- Throttled CFS periods.\\n          (\\n            cpu_cfs_throttled_periods_total - previous_cpu_cfs_throttled_periods_total\\n          ) AS cpu_cfs_throttled_periods_diff,\\n          -- OOM events.\\n          (\\n            oom_events_total - previous_oom_events_total\\n          ) AS oom_events_diff\\n        FROM\\n          (\\n            SELECT\\n              *,\\n              LAG(\\\"__time\\\", 1, \\\"__time\\\") OVER w AS previous_timestamp,\\n              LAG(\\n                cpu_usage_seconds_total,\\n                1,\\n                cpu_usage_seconds_total\\n              ) OVER w AS previous_cpu_usage_seconds_total,\\n              LAG(\\n                cpu_cfs_throttled_seconds_total,\\n                1,\\n                cpu_cfs_throttled_seconds_total\\n              ) OVER w AS previous_cpu_cfs_throttled_seconds_total,\\n              LAG (\\n                cpu_cfs_throttled_periods_total,\\n                1,\\n                cpu_cfs_throttled_periods_total\\n              ) OVER w AS previous_cpu_cfs_throttled_periods_total,\\n              LAG(\\n                cpu_cfs_periods_total,\\n                1,\\n                cpu_cfs_periods_total\\n              ) OVER w AS previous_cpu_cfs_periods_total,\\n              LAG(\\n                oom_events_total,\\n                1,\\n                oom_events_total\\n              ) OVER w AS previous_oom_events_total\\n            FROM\\n              (\\n                SELECT\\n                  \\\"__time\\\",\\n                  k8s_pod_name,\\n                  k8s_container_name,\\n                  falcon_instance,\\n                  functional_domain_instance,\\n                  instance_type,\\n                  zone,\\n                  device,\\n                  container_cpu_cfs_periods_total AS cpu_cfs_periods_total,\\n                  container_cpu_cfs_throttled_periods_total AS cpu_cfs_throttled_periods_total,\\n                  container_cpu_cfs_throttled_seconds_total AS cpu_cfs_throttled_seconds_total,\\n                  container_cpu_usage_seconds_total AS \\\"cpu_usage_seconds_total\\\",\\n                  container_file_descriptors AS file_descriptors,\\n                  container_sockets AS sockets,\\n                  container_oom_events_total AS oom_events_total,\\n                  container_memory_usage_bytes AS memory_usage_bytes\\n                FROM\\n                  cAdvisor\\n                WHERE\\n                  __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\\n                  AND __time <= MILLIS_TO_TIMESTAMP(${__to})\\n                  AND k8s_container_name = 'coreapp'\\n                  AND falcon_instance = '$fi'\\n                  AND functional_domain_instance = '$fd'\\n                  AND k8s_pod_name LIKE '$cell-casam-app-%'\\n              )\\n            WINDOW\\n              w AS (\\n                PARTITION BY\\n                  falcon_instance,\\n                  functional_domain_instance,\\n                  k8s_pod_name,\\n                  k8s_container_name,\\n                  instance_type,\\n                  zone,\\n                  device\\n                ORDER BY\\n                  \\\"__time\\\" ASC\\n              )\\n          )\\n      )\\n  )\\nSELECT\\n  --time_floor(cadvisor_metrics.__time, 'pt12h') AS \\\"timestamp\\\",\\n  time_floor(cadvisor_metrics.__time, 'pt$interval') AS \\\"timestamp\\\",\\n  cadvisor_metrics.k8s_pod_name,\\n  cadvisor_metrics.k8s_container_name,\\n  cadvisor_metrics.falcon_instance,\\n  cadvisor_metrics.functional_domain_instance AS functional_domain,\\n  cadvisor_metrics.instance_type,\\n  cadvisor_metrics.zone,\\n  cadvisor_metrics.device,\\n  AVG(GREATEST(timestamp_seconds_diff, 0)) AS seconds_from_previous_cadvisor_metric,\\n  MAX(container_cpu_cores_request) AS container_cpu_cores_request,\\n  MAX(container_cpu_cores_limit) AS container_cpu_cores_limit,\\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_request) * 100), 0)) AS \\\"CPU Quota Usage\\\",\\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_limit) * 100), 0)) AS cpu_pct_limit_utilization,\\n  MAX(memory_usage_bytes) AS memory_usage_bytes,\\n  MAX(container_memory_bytes_request) AS container_memory_bytes_request,\\n  MAX(container_memory_bytes_limit) AS container_memory_bytes_limit,\\n  MAX(((memory_usage_bytes / container_memory_bytes_request) * 100)) AS container_memory_pct_request_utilization,\\n  MAX(((memory_usage_bytes / container_memory_bytes_limit) * 100)) AS container_memory_pct_limit_utilization,\\n  SUM(GREATEST(oom_events_diff, 0)) AS oom_events_diff,\\n  AVG(GREATEST(cfs_throttled_seconds_diff, 0)/(timestamp_seconds_diff/60)) AS cfs_throttled_seconds_per_minute,\\n  AVG(GREATEST(cpu_cfs_throttled_periods_diff, 0)) AS cpu_cfs_throttled_periods_diff,\\n  AVG(GREATEST(cpu_cfs_periods_diff, 0)) AS cpu_cfs_periods_diff,\\n  AVG(((GREATEST(cpu_cfs_throttled_periods_diff, 0) / cpu_cfs_periods_diff) * 100)) AS cpu_cfs_pct_throttled_periods,\\n  AVG(sockets) AS sockets,\\n  AVG(file_descriptors) AS file_descriptors\\nFROM\\n  cadvisor_metrics\\n  LEFT JOIN kube_state_hourly ON (\\n    cadvisor_metrics.falcon_instance = kube_state_hourly.falcon_instance\\n    AND cadvisor_metrics.functional_domain_instance = kube_state_hourly.functional_domain_instance\\n    AND cadvisor_metrics.k8s_pod_name = kube_state_hourly.k8s_pod_name\\n    AND cadvisor_metrics.k8s_container_name = kube_state_hourly.k8s_container_name\\n    AND DATE_TRUNC('hour', cadvisor_metrics.__time) = kube_state_hourly.__time\\n  )\\nGROUP BY\\n  1, 2, 3, 4, 5, 6, 7, 8\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}",
     "scope1": "$substrate",
     "scope2": "$fi",
     "serviceName": "coreapp_falcon_production"
    }
   ]
  },
  {
   "title": "coreapp Container CPU: Quota and Limit",
   "type": "table",
   "description": "CPU quota and limit for the containers in number of cores.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 123.25 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 131.25 },
   "options": {
    "content": "##### coreapp Container CPU Throttling"
   }
  },
  {
   "title": "coreapp CFS Throttling (seconds throttled per minute)",
   "type": "timeseries",
   "description": "Number of CPU seconds throttled per minute on the containers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132.5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "title": "coreapp CFS Throttling (% time throttled)",
   "type": "timeseries",
   "description": "Percentage of the time period ($interval) where CPU throttling occurred.This is used in conjunction with the number of seconds throttled to understand throttling.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132.5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 140.5 },
   "options": {
    "content": "##### coreapp Container Memory Utilization"
   }
  },
  {
   "title": "coreapp Container Memory: % Limit Used",
   "type": "timeseries",
   "description": "Percentage of memory limit used on the containers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141.75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "title": "coreapp Container Memory: Quota & Limit",
   "type": "table",
   "description": "Memory quota and limit for the container in bytes.",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 141.75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "title": "coreapp Container Memory: OOM Events",
   "type": "table",
   "description": "If any container OOM events during this period the timestamp where it was reported will display in this table. \"No data\" indicates that no OOM events occurred.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 141.75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 149.75 },
   "options": {
    "content": "##### coreapp Resource Utilization"
   }
  },
  {
   "title": "coreapp Open File Descriptors",
   "type": "timeseries",
   "description": "File descriptors open on the container.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "FDs" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "title": "coreapp Open Sockets",
   "type": "timeseries",
   "description": "Sockets open on the container.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "sockets" } },
   "targets": [
    { "panelId": 2058 }
   ]
  },
  {
   "title": "Sidecar Container Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sidecar Container Information",
     "type": "table",
     "description": "Information about the sidecar containers in the CASAM pods.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 168 },
     "options": {
      "content": "##### Sidecar Container CPU Utilization"
     }
    },
    {
     "title": "Sidecar Container CPU Utilization (% of quota)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 169.25 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "builder": {
        "intervals": {
         "intervals": [
          "${__from:date:iso}/${__to:date:iso}"
         ],
         "type": "intervals"
        },
        "query": "WITH\n  kube_state_hourly AS (\n    SELECT\n      DATE_TRUNC('day', kube_state_raw.\"__time\") AS \"__time\",\n      kube_state_raw.k8s_pod_name,\n      kube_state_raw.k8s_container_name,\n      kube_state_raw.falcon_instance,\n      kube_state_raw.functional_domain_instance,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_requests,\n            '$.cpu.core'\n          ) AS DOUBLE\n        )\n      ) AS container_cpu_cores_request,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_requests,\n            '$.memory.byte'\n          ) AS DOUBLE\n        )\n      ) AS container_memory_bytes_request,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_limits,\n            '$.cpu.core'\n          ) AS DOUBLE\n        )\n      ) AS container_cpu_cores_limit,\n      MAX(\n        CAST(\n          JSON_VALUE(\n            kube_state_raw.kube_pod_container_resource_limits,\n            '$.memory.byte'\n          ) AS DOUBLE\n        )\n      ) AS container_memory_bytes_limit\n    FROM\n      (\n        SELECT\n          __time,\n          k8s_pod_name,\n          k8s_container_name,\n          falcon_instance,\n          functional_domain_instance,\n          kube_pod_container_resource_limits,\n          kube_pod_container_resource_requests\n        FROM\n          KubeState\n        WHERE\n          __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\n          AND __time <= MILLIS_TO_TIMESTAMP(${__to})\n          AND k8s_container_name NOT IN ('coreapp')\n          AND falcon_instance = '$fi'\n          AND functional_domain_instance = '$fd'\n          AND k8s_pod_name LIKE '$cell-casam-app%'\n      ) AS kube_state_raw\n    GROUP BY\n      1,\n      2,\n      3,\n      4,\n      5\n    LIMIT 100000\n  ),\n  cadvisor_metrics AS (\n    SELECT\n      __time,\n      previous_timestamp,\n      k8s_pod_name,\n      k8s_container_name,\n      falcon_instance,\n      functional_domain_instance,\n      instance_type,\n      zone,\n      timestamp_seconds_diff,\n      cpu_seconds_diff,\n      cfs_throttled_seconds_diff,\n      cpu_cfs_throttled_periods_diff,\n      cpu_cfs_periods_diff,\n      oom_events_diff,\n      memory_usage_bytes,\n      device,\n      sockets,\n      file_descriptors\n    FROM\n      (\n        SELECT\n          -- Propagate up raw metrics.\n          *,\n          -- Elapsed seconds between metrics.\n          (CAST(TIMESTAMPDIFF (MILLISECOND, previous_timestamp, __time) AS DOUBLE) / 1000) AS timestamp_seconds_diff,\n          (\n            cpu_usage_seconds_total - previous_cpu_usage_seconds_total\n          ) AS cpu_seconds_diff,\n          -- Elapsed CFS throttled seconds.\n          (\n            cpu_cfs_throttled_seconds_total - previous_cpu_cfs_throttled_seconds_total\n          ) AS cfs_throttled_seconds_diff,\n          -- Elapsed CFS periods. (Total, not throttled.)\n          (\n            cpu_cfs_periods_total - previous_cpu_cfs_periods_total\n          ) AS cpu_cfs_periods_diff,\n          -- Throttled CFS periods.\n          (\n            cpu_cfs_throttled_periods_total - previous_cpu_cfs_throttled_periods_total\n          ) AS cpu_cfs_throttled_periods_diff,\n          -- OOM events.\n          (\n            oom_events_total - previous_oom_events_total\n          ) AS oom_events_diff\n        FROM\n          (\n            SELECT\n              *,\n              LAG(\"__time\", 1, \"__time\") OVER w AS previous_timestamp,\n              LAG(\n                cpu_usage_seconds_total,\n                1,\n                cpu_usage_seconds_total\n              ) OVER w AS previous_cpu_usage_seconds_total,\n              LAG(\n                cpu_cfs_throttled_seconds_total,\n                1,\n                cpu_cfs_throttled_seconds_total\n              ) OVER w AS previous_cpu_cfs_throttled_seconds_total,\n              LAG (\n                cpu_cfs_throttled_periods_total,\n                1,\n                cpu_cfs_throttled_periods_total\n              ) OVER w AS previous_cpu_cfs_throttled_periods_total,\n              LAG(\n                cpu_cfs_periods_total,\n                1,\n                cpu_cfs_periods_total\n              ) OVER w AS previous_cpu_cfs_periods_total,\n              LAG(\n                oom_events_total,\n                1,\n                oom_events_total\n              ) OVER w AS previous_oom_events_total\n            FROM\n              (\n                SELECT\n                  \"__time\",\n                  k8s_pod_name,\n                  k8s_container_name,\n                  falcon_instance,\n                  functional_domain_instance,\n                  instance_type,\n                  zone,\n                  device,\n                  container_cpu_cfs_periods_total AS cpu_cfs_periods_total,\n                  container_cpu_cfs_throttled_periods_total AS cpu_cfs_throttled_periods_total,\n                  container_cpu_cfs_throttled_seconds_total AS cpu_cfs_throttled_seconds_total,\n                  container_cpu_usage_seconds_total AS \"cpu_usage_seconds_total\",\n                  container_file_descriptors AS file_descriptors,\n                  container_sockets AS sockets,\n                  container_oom_events_total AS oom_events_total,\n                  container_memory_usage_bytes AS memory_usage_bytes\n                FROM\n                  cAdvisor\n                WHERE\n                  __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\n                  AND __time <= MILLIS_TO_TIMESTAMP(${__to})\n                  AND k8s_container_name NOT IN ('coreapp', 'madkub-refresher', 'keymaker-client-refresher')\n                  AND falcon_instance = '$fi'\n                  AND functional_domain_instance = '$fd'\n                  AND k8s_pod_name LIKE '$cell-casam-app%'\n              )\n            WINDOW\n              w AS (\n                PARTITION BY\n                  falcon_instance,\n                  functional_domain_instance,\n                  k8s_pod_name,\n                  k8s_container_name,\n                  instance_type,\n                  zone,\n                  device\n                ORDER BY\n                  \"__time\" ASC\n              )\n            LIMIT 10000000\n          )\n      )\n  )\nSELECT\n  --time_floor(cadvisor_metrics.__time, 'pt12h') AS \"timestamp\",\n  time_floor(cadvisor_metrics.__time, 'pt$interval') AS \"timestamp\",\n  cadvisor_metrics.k8s_pod_name,\n  cadvisor_metrics.k8s_container_name,\n  cadvisor_metrics.falcon_instance,\n  cadvisor_metrics.functional_domain_instance AS functional_domain,\n  cadvisor_metrics.instance_type,\n  cadvisor_metrics.zone,\n  cadvisor_metrics.device,\n  AVG(GREATEST(timestamp_seconds_diff, 0)) AS seconds_from_previous_cadvisor_metric,\n  MAX(container_cpu_cores_request) AS container_cpu_cores_request,\n  MAX(container_cpu_cores_limit) AS container_cpu_cores_limit,\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_request) * 100), 0)) AS \"CPU Quota Usage\",\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_limit) * 100), 0)) AS cpu_pct_limit_utilization,\n  MAX(memory_usage_bytes) AS memory_usage_bytes,\n  MAX(container_memory_bytes_request) AS container_memory_bytes_request,\n  MAX(container_memory_bytes_limit) AS container_memory_bytes_limit,\n  MAX(((memory_usage_bytes / container_memory_bytes_request) * 100)) AS container_memory_pct_request_utilization,\n  MAX(((memory_usage_bytes / container_memory_bytes_limit) * 100)) AS container_memory_pct_limit_utilization,\n  SUM(GREATEST(oom_events_diff, 0)) AS oom_events_diff,\n  AVG(GREATEST(cfs_throttled_seconds_diff, 0)/(timestamp_seconds_diff/60)) AS cfs_throttled_seconds_per_minute,\n  AVG(GREATEST(cpu_cfs_throttled_periods_diff, 0)) AS cpu_cfs_throttled_periods_diff,\n  AVG(GREATEST(cpu_cfs_periods_diff, 0)) AS cpu_cfs_periods_diff,\n  AVG(((GREATEST(cpu_cfs_throttled_periods_diff, 0) / cpu_cfs_periods_diff) * 100)) AS cpu_cfs_pct_throttled_periods,\n  AVG(sockets) AS sockets,\n  AVG(file_descriptors) AS file_descriptors\nFROM\n  cadvisor_metrics\n  LEFT JOIN kube_state_hourly ON (\n    cadvisor_metrics.falcon_instance = kube_state_hourly.falcon_instance\n    AND cadvisor_metrics.functional_domain_instance = kube_state_hourly.functional_domain_instance\n    AND cadvisor_metrics.k8s_pod_name = kube_state_hourly.k8s_pod_name\n    AND cadvisor_metrics.k8s_container_name = kube_state_hourly.k8s_container_name\n    AND DATE_TRUNC('day', cadvisor_metrics.__time) = kube_state_hourly.__time\n  )\nGROUP BY\n  1, 2, 3, 4, 5, 6, 7, 8\n--LIMIT 1000000",
        "queryType": "sql"
       },
       "eventType": "cAdvisor",
       "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"WITH\\n  kube_state_hourly AS (\\n    SELECT\\n      DATE_TRUNC('day', kube_state_raw.\\\"__time\\\") AS \\\"__time\\\",\\n      kube_state_raw.k8s_pod_name,\\n      kube_state_raw.k8s_container_name,\\n      kube_state_raw.falcon_instance,\\n      kube_state_raw.functional_domain_instance,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_requests,\\n            '$.cpu.core'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_cpu_cores_request,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_requests,\\n            '$.memory.byte'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_memory_bytes_request,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_limits,\\n            '$.cpu.core'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_cpu_cores_limit,\\n      MAX(\\n        CAST(\\n          JSON_VALUE(\\n            kube_state_raw.kube_pod_container_resource_limits,\\n            '$.memory.byte'\\n          ) AS DOUBLE\\n        )\\n      ) AS container_memory_bytes_limit\\n    FROM\\n      (\\n        SELECT\\n          __time,\\n          k8s_pod_name,\\n          k8s_container_name,\\n          falcon_instance,\\n          functional_domain_instance,\\n          kube_pod_container_resource_limits,\\n          kube_pod_container_resource_requests\\n        FROM\\n          KubeState\\n        WHERE\\n          __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\\n          AND __time <= MILLIS_TO_TIMESTAMP(${__to})\\n          AND k8s_container_name NOT IN ('coreapp')\\n          AND falcon_instance = '$fi'\\n          AND functional_domain_instance = '$fd'\\n          AND k8s_pod_name LIKE '$cell-casam-app%'\\n      ) AS kube_state_raw\\n    GROUP BY\\n      1,\\n      2,\\n      3,\\n      4,\\n      5\\n    LIMIT 100000\\n  ),\\n  cadvisor_metrics AS (\\n    SELECT\\n      __time,\\n      previous_timestamp,\\n      k8s_pod_name,\\n      k8s_container_name,\\n      falcon_instance,\\n      functional_domain_instance,\\n      instance_type,\\n      zone,\\n      timestamp_seconds_diff,\\n      cpu_seconds_diff,\\n      cfs_throttled_seconds_diff,\\n      cpu_cfs_throttled_periods_diff,\\n      cpu_cfs_periods_diff,\\n      oom_events_diff,\\n      memory_usage_bytes,\\n      device,\\n      sockets,\\n      file_descriptors\\n    FROM\\n      (\\n        SELECT\\n          -- Propagate up raw metrics.\\n          *,\\n          -- Elapsed seconds between metrics.\\n          (CAST(TIMESTAMPDIFF (MILLISECOND, previous_timestamp, __time) AS DOUBLE) / 1000) AS timestamp_seconds_diff,\\n          (\\n            cpu_usage_seconds_total - previous_cpu_usage_seconds_total\\n          ) AS cpu_seconds_diff,\\n          -- Elapsed CFS throttled seconds.\\n          (\\n            cpu_cfs_throttled_seconds_total - previous_cpu_cfs_throttled_seconds_total\\n          ) AS cfs_throttled_seconds_diff,\\n          -- Elapsed CFS periods. (Total, not throttled.)\\n          (\\n            cpu_cfs_periods_total - previous_cpu_cfs_periods_total\\n          ) AS cpu_cfs_periods_diff,\\n          -- Throttled CFS periods.\\n          (\\n            cpu_cfs_throttled_periods_total - previous_cpu_cfs_throttled_periods_total\\n          ) AS cpu_cfs_throttled_periods_diff,\\n          -- OOM events.\\n          (\\n            oom_events_total - previous_oom_events_total\\n          ) AS oom_events_diff\\n        FROM\\n          (\\n            SELECT\\n              *,\\n              LAG(\\\"__time\\\", 1, \\\"__time\\\") OVER w AS previous_timestamp,\\n              LAG(\\n                cpu_usage_seconds_total,\\n                1,\\n                cpu_usage_seconds_total\\n              ) OVER w AS previous_cpu_usage_seconds_total,\\n              LAG(\\n                cpu_cfs_throttled_seconds_total,\\n                1,\\n                cpu_cfs_throttled_seconds_total\\n              ) OVER w AS previous_cpu_cfs_throttled_seconds_total,\\n              LAG (\\n                cpu_cfs_throttled_periods_total,\\n                1,\\n                cpu_cfs_throttled_periods_total\\n              ) OVER w AS previous_cpu_cfs_throttled_periods_total,\\n              LAG(\\n                cpu_cfs_periods_total,\\n                1,\\n                cpu_cfs_periods_total\\n              ) OVER w AS previous_cpu_cfs_periods_total,\\n              LAG(\\n                oom_events_total,\\n                1,\\n                oom_events_total\\n              ) OVER w AS previous_oom_events_total\\n            FROM\\n              (\\n                SELECT\\n                  \\\"__time\\\",\\n                  k8s_pod_name,\\n                  k8s_container_name,\\n                  falcon_instance,\\n                  functional_domain_instance,\\n                  instance_type,\\n                  zone,\\n                  device,\\n                  container_cpu_cfs_periods_total AS cpu_cfs_periods_total,\\n                  container_cpu_cfs_throttled_periods_total AS cpu_cfs_throttled_periods_total,\\n                  container_cpu_cfs_throttled_seconds_total AS cpu_cfs_throttled_seconds_total,\\n                  container_cpu_usage_seconds_total AS \\\"cpu_usage_seconds_total\\\",\\n                  container_file_descriptors AS file_descriptors,\\n                  container_sockets AS sockets,\\n                  container_oom_events_total AS oom_events_total,\\n                  container_memory_usage_bytes AS memory_usage_bytes\\n                FROM\\n                  cAdvisor\\n                WHERE\\n                  __time >= TIME_SHIFT(MILLIS_TO_TIMESTAMP(${__from}), 'pt10m', -1)\\n                  AND __time <= MILLIS_TO_TIMESTAMP(${__to})\\n                  AND k8s_container_name NOT IN ('coreapp', 'madkub-refresher', 'keymaker-client-refresher')\\n                  AND falcon_instance = '$fi'\\n                  AND functional_domain_instance = '$fd'\\n                  AND k8s_pod_name LIKE '$cell-casam-app%'\\n              )\\n            WINDOW\\n              w AS (\\n                PARTITION BY\\n                  falcon_instance,\\n                  functional_domain_instance,\\n                  k8s_pod_name,\\n                  k8s_container_name,\\n                  instance_type,\\n                  zone,\\n                  device\\n                ORDER BY\\n                  \\\"__time\\\" ASC\\n              )\\n            LIMIT 10000000\\n          )\\n      )\\n  )\\nSELECT\\n  --time_floor(cadvisor_metrics.__time, 'pt12h') AS \\\"timestamp\\\",\\n  time_floor(cadvisor_metrics.__time, 'pt$interval') AS \\\"timestamp\\\",\\n  cadvisor_metrics.k8s_pod_name,\\n  cadvisor_metrics.k8s_container_name,\\n  cadvisor_metrics.falcon_instance,\\n  cadvisor_metrics.functional_domain_instance AS functional_domain,\\n  cadvisor_metrics.instance_type,\\n  cadvisor_metrics.zone,\\n  cadvisor_metrics.device,\\n  AVG(GREATEST(timestamp_seconds_diff, 0)) AS seconds_from_previous_cadvisor_metric,\\n  MAX(container_cpu_cores_request) AS container_cpu_cores_request,\\n  MAX(container_cpu_cores_limit) AS container_cpu_cores_limit,\\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_request) * 100), 0)) AS \\\"CPU Quota Usage\\\",\\n  AVG(GREATEST(((cpu_seconds_diff / timestamp_seconds_diff / container_cpu_cores_limit) * 100), 0)) AS cpu_pct_limit_utilization,\\n  MAX(memory_usage_bytes) AS memory_usage_bytes,\\n  MAX(container_memory_bytes_request) AS container_memory_bytes_request,\\n  MAX(container_memory_bytes_limit) AS container_memory_bytes_limit,\\n  MAX(((memory_usage_bytes / container_memory_bytes_request) * 100)) AS container_memory_pct_request_utilization,\\n  MAX(((memory_usage_bytes / container_memory_bytes_limit) * 100)) AS container_memory_pct_limit_utilization,\\n  SUM(GREATEST(oom_events_diff, 0)) AS oom_events_diff,\\n  AVG(GREATEST(cfs_throttled_seconds_diff, 0)/(timestamp_seconds_diff/60)) AS cfs_throttled_seconds_per_minute,\\n  AVG(GREATEST(cpu_cfs_throttled_periods_diff, 0)) AS cpu_cfs_throttled_periods_diff,\\n  AVG(GREATEST(cpu_cfs_periods_diff, 0)) AS cpu_cfs_periods_diff,\\n  AVG(((GREATEST(cpu_cfs_throttled_periods_diff, 0) / cpu_cfs_periods_diff) * 100)) AS cpu_cfs_pct_throttled_periods,\\n  AVG(sockets) AS sockets,\\n  AVG(file_descriptors) AS file_descriptors\\nFROM\\n  cadvisor_metrics\\n  LEFT JOIN kube_state_hourly ON (\\n    cadvisor_metrics.falcon_instance = kube_state_hourly.falcon_instance\\n    AND cadvisor_metrics.functional_domain_instance = kube_state_hourly.functional_domain_instance\\n    AND cadvisor_metrics.k8s_pod_name = kube_state_hourly.k8s_pod_name\\n    AND cadvisor_metrics.k8s_container_name = kube_state_hourly.k8s_container_name\\n    AND DATE_TRUNC('day', cadvisor_metrics.__time) = kube_state_hourly.__time\\n  )\\nGROUP BY\\n  1, 2, 3, 4, 5, 6, 7, 8\\n--LIMIT 1000000\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}",
       "scope1": "$substrate",
       "scope2": "$fi",
       "scope3": "SCOPE3_CHANGE_ME",
       "serviceName": "coreapp_falcon_production"
      }
     ]
    },
    {
     "title": "Sidecar Container CPU: Quota and Limit",
     "type": "table",
     "description": "CPU quota and limit for the containers in number of cores.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 169.25 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 177.25 },
     "options": {
      "content": "##### Sidecar Container CPU Throttling"
     }
    },
    {
     "title": "Sidecar Container CFS Throttling (seconds throttled per minute)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178.5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "title": "Sidecar Container CFS Throttling (% time throttled)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178.5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 186.5 },
     "options": {
      "content": "##### Sidecar Container Memory Utilization"
     }
    },
    {
     "title": "Sidecar Container Memory: % Limit Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187.75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "title": "Sidecar Container Memory: Quota & Limit",
     "type": "table",
     "description": "Memory quota and limit for the container in bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 187.75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "title": "Sidecar Container Memory: OOM Events",
     "type": "table",
     "description": "If any container OOM events during this period the timestamp where it was reported will display in this table. \"No data\" indicates that no OOM events occurred.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 187.75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 1.25, "w": 24, "x": 0, "y": 195.75 },
     "options": {
      "content": "##### Sidecar Resource Utilization"
     }
    },
    {
     "title": "Sidecar Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "FDs" } },
     "targets": [
      { "panelId": 2088 }
     ]
    },
    {
     "title": "Sidecar Open Sockets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "fieldConfig": { "defaults": { "unit": "sockets" } },
     "targets": [
      { "panelId": 2088 }
     ]
    }
   ]
  },
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  { "title": "App Garbage Collection", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "GC Pause Times By Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-System-name2-AveGCUsage.OneMinuteAverage{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,\n    #$interval-$agg#),\n#k8s_pod_name#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Allocation Rate by Container (bytes / minute, $interval $agg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    SCALE(\n      CULL_BELOW(\n        RATE(\n          $start:$end:core.$substrate.$fi.$fd:Jvm.totalAllocatedMb.Value{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max\n        ),\n        #0.0001#,#value#\n      ),\n      #1048576#),\n    #$interval-$agg#\n  ),\n  #k8s_pod_name#\n)\n",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Old Gen Heap after GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    $start:$end:core.$substrate.$fi.$fd:Jvm.lastOldGenAfterGcSizeMb.Value{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,\n    #$interval-$agg#\n  ),\n  #k8s_pod_name#\n)\n",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "text",
   "description": "Non-heap memory usage, some fields are not available when tiered compilation is enabled.",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 }
  },
  {
   "title": "Code Cache/Heap (MB) by host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "CULL_BELOW(\n  ALIASBYTAG(\n    DOWNSAMPLE(\n      $start:$end:core.$substrate.$fi.$fd:Jvm.lastCodeCacheAfterGcSizeMb.Value{cell=$cell,role=app}:none:1m-max,\n      #$interval-$agg#\n    ),\n    #k8s_pod_name#\n  ),\n#0#,#value#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "CULL_BELOW(\n  MAX(\n    $start:$end:core.$substrate.$fi.$fd:Jvm.CodeCacheMaxMb.Value{cell=$cell,role=app}:none:1m-max\n  ),\n#0#,#value#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Metaspace Usage (MB) by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    $start:$end:core.$substrate.$fi.$fd:java-lang_name-Metaspace-type-MemoryPool.Usage_used{cell=$cell,role=app,k8s_pod_name=*}:max:1m-max,\n    #$interval-$agg#\n  ),\n  #k8s_pod_name#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "MAX($start:$end:core.$substrate.$fi.$fd:java-lang_name-Metaspace-type-MemoryPool.Usage_max{cell=$cell,role=app,k8s_pod_name=*}:max:1m-max)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Non-Heap Memory Usage (MB) by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    $start:$end:core.$substrate.$fi.$fd:java-lang_type-Memory.NonHeapMemoryUsage_used{cell=$cell,role=app,k8s_pod_name=*}:max:1m-max,\n    #$interval-$agg#\n  ),\n  #k8s_pod_name#\n)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "MAX($start:$end:core.$substrate.$fi.$fd:java-lang_type-Memory.NonHeapMemoryUsage_max{cell=$cell,role=app,k8s_pod_name=*}:max:$interval-$agg)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "General", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 } },
  {
   "title": "App Tier Uptime",
   "type": "graph",
   "description": "Application server JVM uptime by host.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYTAG(\n    $start:$end:core.$substrate.$fi.$fd:java-lang_type-Runtime.Uptime{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,\n    #k8s_pod_name#\n  ),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connection Pool Errors by App Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n    DOWNSAMPLE(\n        CULL_BELOW(\n          RATE(\n            $start:$end:core.$substrate.$fi.$fd:SFDC_type-ServerMetrics.ExtendedCounterMetric-CONNECTION_POOL_ERRORS{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n          ),\n          #0#,#value#\n      ),\n      #$interval-$agg#\n    ),\n    #k8s_pod_name#\n  )",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Jetty Status", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "HTTP Status Code (count / minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n    SUM(\n        RATE(\n            $start:$end:core.$substrate.$fi.$fd:jetty.sh.response.2xx{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n        ),\n    #union#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n    SUM(\n        RATE(\n            $start:$end:core.$substrate.$fi.$fd:jetty.sh.response.3xx{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n        ),\n    #union#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n    SUM(\n        RATE(\n            $start:$end:core.$substrate.$fi.$fd:jetty.sh.response.4xx{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg\n        ),\n    #union#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n    SUM(\n        RATE(\n            $start:$end:core.$substrate.$fi.$fd:jetty.sh.response.5xx{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max\n        ),\n    #union#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Jetty QTP Busy Threads",
   "type": "timeseries",
   "description": "Number of busy QTP (queued thread pool) threads by host.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n    ALIASBYTAG(\n        $start:$end:core.$substrate.$fi.$fd:jetty.qtp.busythreads{role=app,cell=$cell,k8s_pod_name=*}:max:1m-max,#k8s_pod_name#\n    ),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Logging", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 } },
  {
   "title": "Log Volume (characters per minute, $interval $agg)",
   "type": "timeseries",
   "description": "Quantity of logging across the instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIAS(\n  SUM(\n    $start:$end:core.$substrate.$fi.$fd:ServiceProtection.Logging.Total__Characters__Logged{role=app,cell=$cell,k8s_pod_name=*}:sum:$interval-$agg,#UNION#\n  )\n,#total_characters_logged#,#literal#)",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  $start:$end:core.$substrate.$fi.$fd:ServiceProtection.Logging.Total__Characters__Logged{role=app,cell=$cell,k8s_pod_name=*}:sum:$interval-$agg,#k8s_pod_name#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Asynchronous Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 } },
  {
   "title": "MQ Utilization By Node",
   "type": "graph",
   "description": "Percentage of MQ threads in use by node. Values near 100% indicate a lack of threads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "GROUPBY(\n  GROUPBY(\n    $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-MessageQueue-name2-MqDequeueTimeSpentInHandlerMsRacNode*.Count{role=app,cell=$cell,k8s_pod_name=*}:sum:5m-sum,#(Node[0-9]+)#,#SUM#\n  ),\n  GROUPBY(\n    $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-MessageQueue-name2-MqActiveThreadsPerRacNode*.Value{cell=$cell}:max:5m-max,#(Node[0-9]+)#,#SCALE#,#300000#\n  ),\n  #(Node[0-9]+)#,#DIVIDE#,#UNION#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Active MQ Threads by Container",
   "type": "graph",
   "description": "Number of MQ threads for all nodes actively processing messages on average during a minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  ALIASBYTAG(\n    DIVIDE(\n      GROUPBYTAG(\n        $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-MessageQueue-name2-MqDequeueTimeSpentInHandlerMsRacNode*.Count{role=app,cell=$cell,k8s_pod_name=*}:avg:1m-avg,#k8s_pod_name#,#SUM#,#union#\n      ),\n      #60000#\n    ),\n    #k8s_pod_name#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dashboard Refresh Message Latency (DASHBOARD_COMPONENT_UPDATE_SMALL) by DB Node",
   "type": "graph",
   "description": "Dequeue latency of DASHBOARD_COMPONENT_UPDATE_SMALL messages.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  GROUPBY(\n    $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-MessageQueue-name2-DequeueLatencyForDashboardComponentUpdateSmall*.Value{cell=$cell}:max:1m-max,#SFDC_type-Stats-name1-MessageQueue-name2-DequeueLatencyForDashboardComponentUpdateSmall(\\S+).Value#,#join#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Apex Future Message Latency (APEX_FUTURE) by DB Node",
   "type": "graph",
   "description": "Dequeue latency of APEX_FUTURE messages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  GROUPBY(\n    $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-MessageQueue-name2-DequeueLatencyForApexFuture*.Value{cell=$cell}:max:1m-max,#SFDC_type-Stats-name1-MessageQueue-name2-DequeueLatencyForApexFuture(\\S+).Value#,#join#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "QPID Broker Heap Usage",
   "type": "graph",
   "description": "Percent of QPID broker heap used by host.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "ALIASBYTAG(\n  DOWNSAMPLE(\n    GROUPBYTAG(\n      $start:$end:core.$substrate.$fi.$fd:mqService.broker.oldGenHeapUsagePercent{role=app,cell=$cell,k8s_pod_name=*,broker=*}:max:1m-max,#broker#,#MAX#\n    ),\n    #$interval-$agg#\n  )\n,#broker#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Signature / ProM / SFDC Org Impact",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 239 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 240 },
   "options": {
    "content": "This section shows metrics derived from \norg-specific metrics on the target instance. \nMetrics for orgs that have purchased Signature\n(SIG/MCS) or Proactive Monitoring (ProM) \nare displayed here as well as other orgs, \nprimarily SFDC-owned orgs, that have metrics\nenabled. Note there is not a good way to \ndistinguish between the different types \nof orgs on this dashboard."
   }
  },
  { "title": "General", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 242 } },
  {
   "title": "Request Rate (count / second)",
   "type": "graph",
   "description": "Number of requests completing per second by org.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  DIVIDE(\n    GROUPBY(\n      $start:$end:core_prom_prod.*.*.*:OrgSpecificMetrics-???????????????.LogMetric.COUNT.-.NRT.COUNT.Count{cell=$cell}:none:1m-sum,\n      #OrgSpecificMetrics-(\\S{15}).LogMetric.COUNT.-.NRT.COUNT.Count#,#SUM#,#UNION#\n    ),\n  #60#),\n#$interval-$agg#)\n\n\n\n\n\n\n",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "APT (ms / request)",
   "type": "graph",
   "description": "APT (server-side response time) broken down by org.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  GROUPBY(\n    GROUPBY(\n      $start:$end:core_prom_prod.$substrate.$fi.$fd:OrgSpecificMetrics-???????????????.LogMetric.WALL_TIME.-.NRT.COUNT.Count{cell=$cell}:none:1m-sum,\n      #OrgSpecificMetrics-(\\S{15}).LogMetric.WALL_TIME.-.NRT.COUNT.Count#,#SUM#,#UNION#\n    ),\n    GROUPBY(\n      $start:$end:core_prom_prod.$substrate.$fi.$fd:OrgSpecificMetrics-???????????????.LogMetric.COUNT.-.NRT.COUNT.Count{cell=$cell}:none:1m-sum,\n      #OrgSpecificMetrics-(\\S{15}).LogMetric.COUNT.-.NRT.COUNT.Count#,#SUM#,#UNION#\n    ),\n  #(\\S{15})#,#divide#,#union#,#0#),\n#$interval-$agg#)\n",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connection Pool Errors (count / minute)",
   "type": "graph",
   "description": "Number of connection pool errors per minute by org.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  DIVIDE(\n    GROUPBY(\n      $start:$end:core_prom_prod.$substrate.$fi.$fd:OrgSpecificMetrics-???????????????.ExtendedCounterMetric.CONNECTION_POOL_ERRORS.-.NRT.COUNT.Count{cell=$cell}:none:1m-sum,\n      #OrgSpecificMetrics-(\\S{15}).ExtendedCounterMetric.CONNECTION_POOL_ERRORS.-.NRT.COUNT.Count#,#SUM#,#UNION#\n    ),\n  #60#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Concurrent Apex Errors (count / minute)",
   "type": "graph",
   "description": "Number of concurrent apex errors per minute by org.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 251 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  DIVIDE(\n    GROUPBY(\n      $start:$end:core_prom_prod.$substrate.$fi.$fd:OrgSpecificMetrics-???????????????.ExtendedCounterMetric.CONCURRENT_APEX_ERRORS.-.NRT.COUNT.Count{cell=$cell}:none:1m-sum,\n      #OrgSpecificMetrics-(\\S{15}).ExtendedCounterMetric.CONCURRENT_APEX_ERRORS.-.NRT.COUNT.Count#,#SUM#,#UNION#\n    ),\n  #60#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Concurrent UI Errors (count / minute)",
   "type": "graph",
   "description": "Number of concurrent UI errors per minute by org.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  DIVIDE(\n    GROUPBY(\n      $start:$end:core_prom_prod.$substrate.$fi.$fd:OrgSpecificMetrics-???????????????.ExtendedCounterMetric.CONCURRENT_UI_REQUEST_ERRORS.-.NRT.COUNT.Count{cell=$cell}:none:1m-sum,\n      #OrgSpecificMetrics-(\\S{15}).ExtendedCounterMetric.CONCURRENT_UI_REQUEST_ERRORS.-.NRT.COUNT.Count#,#SUM#,#UNION#\n    ),\n  #60#),\n#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Search Metrics", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 267 } },
  {
   "title": "Search Query Volume (count / minute)",
   "type": "graph",
   "description": "Number of search queries per minute by org.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  GROUPBY(\n    RATE(\n      $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Query_Count_???????????????.Count{cell=$cell,k8s_pod_name=*}:sum:1m-avg\n    ),\n    #SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Query_Count_(\\S{15}).Count#,#sum#,#union#\n  )\n,#$interval-$agg#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Search Query Reliability (failed % / minute)",
   "type": "graph",
   "description": "Number of failed or fallback search queries per minute by org. (A fallback query is one that uses the database rather than the search tier due to the latter's unavailability.)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 268 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "DOWNSAMPLE(\n  GROUPBY(\n    GROUPBY(\n      RATE(\n        $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Query_Failure_Count_???????????????.Count{cell=$cell,k8s_pod_name=*}:avg:1m-avg\n      ),\n      #SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Query_Failure_Count_(\\S{15}).Count#,#sum#,#union#\n    ),\n    GROUPBY(\n      RATE(\n        $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Query_Count_???????????????.Count{cell=$cell,k8s_pod_name=*}:avg:1m-avg\n      ),\n      #SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Query_Count_(\\S{15}).Count#,#sum#,#union#\n    ),\n    #(\\S{15})#,#divide#,#union#,#0#\n  ),\n  #$interval-$agg#\n)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Search Indexing Delay",
   "type": "graph",
   "description": "Number of \"late\" rows by org. Note that rows could represent a batch of records waiting to be index. Ref. https://salesforce.quip.com/b2waAexlVRxC",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "queryMode": "expression",
     "rawSql": "GROUPBY(\n  DOWNSAMPLE(\n      $start:$end:core.$substrate.$fi.$fd:SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Indexing_late_rows_???????????????_SolrLive.CurrentSize{cell=$cell}:max:1m-max\n  ,#$interval-$agg#),\n#SFDC_type-Stats-name1-Search-name2-Client-name3-SignatureOrg_Indexing_late_rows_(\\S+)_SolrLive.CurrentSize#,#JOIN#)",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  }
 ]
}